name: Mark stale issues and pull requests

on:
  schedule:
    - cron: '15 5 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v8
      with:
        days-before-stale: 30
        days-before-close: -1
        stale-issue-message: ''
        stale-pr-message: ''
